wandb_project: kaggle-ventilator-pressure-prediction
experiment_name: meta_LSTM
is_dual_head: False
seq_len: 40

topk: 3 #1 #3
create_features: False
create_matrix: False

training_type:
  loss: truncated #complete truncated
  is_smoothing: False

normalization:
  is_norm: True
  is_log_transform: False

dataset:
  train:
    class: VentilatorDataRegression
    kwargs:
      categorical_columns: ['u_out','R','C']
      numerical_columns: ['R_1','C_1','time_step', 'u_in','preds']
      target_column: pressure

  val:
    class: VentilatorDataRegression
    kwargs:
      categorical_columns: ['u_out','R','C']
      numerical_columns: ['R_1','C_1','time_step', 'u_in','preds']
      target_column: pressure
  test:
    class: VentilatorDataRegression
    kwargs:
      categorical_columns: ['u_out','R','C']
      numerical_columns: ['R_1','C_1','time_step', 'u_in','preds']



esr:
  monitor: val_MAE
  min_delta: 0.0001
  patience: 100
  verbose: False
  mode: min

num_epochs: &n_epochs 100 #300

batch_size:
    train: 32 #128 #32
    val: 512 #256 64
num_workers:
    train: 8
    val: 8

optimizer:
    optim_class: Adam
    optim_kwargs:
        lr: &learning_rate 1e-4 #2e-4 #1e-3

start_lr: *learning_rate
last_lr: 5e-5

# schedular:
#     schedular_class: MultiplicativeLR
#     schedular_interval: epoch
#     # scheduler_kwargs:

schedular:
    schedular_class: OneCycleLR
    schedular_interval: step
    scheduler_kwargs:
      max_lr: *learning_rate
      epochs: *n_epochs
      div_factor: 30
      pct_start: 0.2
      final_div_factor: 50



loss:
  class: L1Loss
  kwargs:
    reduction: mean

mp_training: False

model:
  class: LSTMModel
  kwargs:
    embedding_layer:
      u_out:
        num_embeddings: 2
        embedding_dim: 4
      R:
        num_embeddings: 3
        embedding_dim: 4
      C:
        num_embeddings: 3
        embedding_dim: 4
    input_dim: &in_dim 17
    rnn_layer:
      class: LSTM
      kwargs:
        input_size: *in_dim
        hidden_size: 256
        num_layers: 2
        batch_first: true
        bidirectional: true
        dropout: 0
    rnn_init:
      class: InitRNNWeights
      kwargs:
        init_type: xavier
    output_dim: 1








